# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish Maven Package

on:
  workflow_dispatch: 
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      id: build
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      id: github-deploy
      if: ${{ always() && steps.build.conclusion == 'success' }}
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -D altDeploymentRepository=github::default::https://maven.pkg.github.com/SYpiece/OJOCL
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Check Error
      if: ${{ always() && steps.github-deploy.conclusion == 'failure' }}
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -D altDeploymentRepository=github::default::https://maven.pkg.github.com/SYpiece/OJOCL -X
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to Maven Central
      id: maven-central-deploy
      if: ${{ always() && steps.build.conclusion == 'success' }}
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -D altDeploymentRepository=central::default::https://s01.oss.sonatype.org/service/local/staging/deploy/maven2
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    - name: Check Error
      if: ${{ always() && steps.maven-central-deploy.conclusion == 'failure' }}
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -D altDeploymentRepository=central::default::https://s01.oss.sonatype.org/service/local/staging/deploy/maven2 -X
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}