
name: Publish to Maven Central
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java 8, Maven and GPG
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: 'central'
          server-username: 'USERNAME'
          server-password: 'PASSWORD'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: 'PASSPHRASE'

      - run: sudo apt install -y pocl-opencl-icd

      - name: Build with Maven
        id: build
        run: mvn -B package --file pom.xml

      - run: "cat ~/.m2/settings.xml"

      - name: Publish to Maven Central
        run: "mvn deploy -P central -X"
        env:
          USERNAME: ${{ secrets.MAVEN_USERNAME }}
          PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
