
name: Publish to Maven Central
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Java 8, Maven and GPG
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: 'ossrh'
#          server-username: ${{ secrets.MAVEN_USERNAME }}
#          server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          settings-path: ${{ github.workplace }}

      - name: Build with Maven
        id: build
        run: mvn -B package --file pom.xml

      - name: Publish to Maven Central
        run: "mvn deploy \
          -s $GITHUB_WORKSPACE/settings.xml \
          -D altDeploymentRepository=central::default::https://s01.oss.sonatype.org/service/local/staging/deploy/maven2 -X"