
name: Publish to GitHub Packages
on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: 'github'
          server-username: 'USERNAME'
          server-password: 'PASSWORD'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - run: "cat ~/.m2/settings.xml"

#      - name: Publish to GitHub Packages
#        id: publish
#        run: "mvn \
#          deploy \
#          -D altDeploymentRepository=github::default::https://maven.pkg.github.com/SYpiece/OJOCL -X"
#        env:
#          USERNAME: ${{ github.actor }}
#          PASSWORD: ${{ github.token }}
#          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to GitHub Packages
        id: publish
        run: "mvn deploy -P github -X"
        env:
          USERNAME: ${{ github.actor }}
          PASSWORD: ${{ github.token }}
